### PR TITLE
Fix path for PHP config

### LINKED ISSUE #4: composer install command breaks on missing extensions
I've enabled some third-party extension as mentioned by https://devcenter.heroku.com/articles/php-support#using-optional-extensions. But when I try to build the application through Docker, the following error occurs:

```bash
Building web...
Step 0 : FROM heroku/php
# Executing 6 build triggers
Trigger 0, COPY composer.lock /app/user/
Step 0 : COPY composer.lock /app/user/
 ---> Using cache
Trigger 1, COPY composer.json /app/user/
Step 0 : COPY composer.json /app/user/
 ---> Using cache
Trigger 2, RUN composer install --no-scripts
Step 0 : RUN composer install --no-scripts
 ---> Running in b37f3bf2f5e2
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested PHP extension ext-apcu * is missing from your system.
```

Why do you run `composer install --no-scripts`? As it is also ran inside the buildpack compile script. And if it is required, can it be run with `composer install --no-scripts ----ignore-platform-reqs`?

### PR DESCRIPTION
**Pull request by JakeChampion**
Fixes #4

### CODE REVIEW

**Comment by friism** [comment]
@dzuelke if you have time, can you take a look at this? /cc @hunterloftis @niklasrichardson

**Comment by dzuelke** [comment]
Roger, will tackle ASAP.

**Comment by niklasrichardson** [comment]
Thanks Michael.

## 

Niklas Richardson
Customer Solutions Architect
Heroku

niklas@heroku.com
www.heroku.com

**Comment by boboldehampsink** [comment]
I'm experiencing issues because of this too

**Comment by boboldehampsink** [comment]
This doesn't work for me. Changing the path to /app/.heroku/php/etc/php/conf.d/php.ini does.

**Comment by JakeChampion** [comment]
@boboldehampsink Thanks, updated.

**Comment by elspethsoup** [comment]
This fix also worked for me.

**Comment by boboldehampsink** [comment]
It's been 3 weeks guys (@heroku)

**Comment by dzuelke** [comment]
Writing to `conf.d/` only worked due to special circumstances; the first `php.ini` path was correct, but the buildpack's boot scripts overrode the main INI. Fixed there now (heroku/heroku-buildpack-php@0b67f57d3e9fbe6c8229356b628c3cf8abee535e), and #4 got the accompanying fix to `Dockerfile`.

**Comment by triblondon** [comment]
@dzuelke Jake's patch works for my but the latest `heroku/php` dockerfile following your fix does not.  I get the following error:

```
Step 0 : FROM heroku/php
# Executing 6 build triggers
Trigger 0, COPY composer.lock /app/user/
Step 0 : COPY composer.lock /app/user/
 ---> Using cache
Trigger 1, COPY composer.json /app/user/
Step 0 : COPY composer.json /app/user/
 ---> Using cache
Trigger 2, RUN composer install --no-scripts
Step 0 : RUN composer install --no-scripts
 ---> Running in 930df161ddfb
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested PHP extension ext-mbstring * is missing from your system.
```

So it seems to me that the error is still present.

**Comment by dzuelke** [comment]
Did you run "composer update" to get the latest build pack package update?

**Comment by dzuelke** [comment]
Ah never mind. Different issue I think. I'll take another look.

**Comment by dzuelke** [comment]
Works for me:

```
~ $ mkdir docker-php-pr-5-test
~ $ cd docker-php-pr-5-test/
docker-php-pr-5-test $ composer require --no-update ext-mbstring:*
./composer.json has been created
docker-php-pr-5-test $ composer require --dev heroku/heroku-buildpack-php:*
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing heroku/heroku-buildpack-php (v82)
    Loading from cache

Writing lock file
Generating autoload files
docker-php-pr-5-test $ rm -rf vendor/
docker-php-pr-5-test $ echo "web: vendor/bin/heroku-php-apache2" > Procfile
docker-php-pr-5-test $ echo "hi" > index.php
docker-php-pr-5-test $ heroku docker:init -i heroku/php
docker-php-pr-5-test $ docker-compose build
Building web...
Step 0 : FROM heroku/php
# Executing 6 build triggers
Trigger 0, COPY composer.lock /app/user/
Step 0 : COPY composer.lock /app/user/
Trigger 1, COPY composer.json /app/user/
Step 0 : COPY composer.json /app/user/
Trigger 2, RUN composer install --no-scripts
Step 0 : RUN composer install --no-scripts
 ---> Running in d22d84db53d8
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
  - Installing heroku/heroku-buildpack-php (v82)
    Downloading: 100%         

Generating autoload files
Trigger 3, RUN composer show --installed heroku/heroku-buildpack-php || { echo 'Your composer.json must have "heroku/heroku-buildpack-php" as a "require-dev" dependency.'; exit 1; }
Step 0 : RUN composer show --installed heroku/heroku-buildpack-php || { echo 'Your composer.json must have "heroku/heroku-buildpack-php" as a "require-dev" dependency.'; exit 1; }
 ---> Running in 6006026b566b
name     : heroku/heroku-buildpack-php
descrip. : Toolkit for starting a PHP application locally, with or without foreman, using the same config for PHP/HHVM and Apache2/Nginx as on Heroku
keywords : apache, apache2, foreman, heroku, hhvm, nginx, php
versions : * v82
type     : library
license  : MIT
source   : [git] https://github.com/heroku/heroku-buildpack-php.git ce2b40b0ecf99c2d4fb4cee9edffc5a80cb8b274
dist     : [zip] https://api.github.com/repos/heroku/heroku-buildpack-php/zipball/ce2b40b0ecf99c2d4fb4cee9edffc5a80cb8b274 ce2b40b0ecf99c2d4fb4cee9edffc5a80cb8b274
names    : heroku/heroku-buildpack-php
Trigger 4, ADD . /app/user/
Step 0 : ADD . /app/user/
Trigger 5, RUN cat composer.json | python -c 'import sys,json; sys.exit("post-install-cmd" not in json.load(sys.stdin).get("scripts", {}));' && composer run-script post-install-cmd || true
Step 0 : RUN cat composer.json | python -c 'import sys,json; sys.exit("post-install-cmd" not in json.load(sys.stdin).get("scripts", {}));' && composer run-script post-install-cmd || true
 ---> Running in e6127f1d69c2
 ---> 427cf28afad4
Removing intermediate container c74b8cd14433
Removing intermediate container d332a90c42a5
Removing intermediate container d22d84db53d8
Removing intermediate container 6006026b566b
Removing intermediate container cd43aa58c198
Removing intermediate container e6127f1d69c2
Successfully built 427cf28afad4
Building shell...
Step 0 : FROM heroku/php
# Executing 6 build triggers
Trigger 0, COPY composer.lock /app/user/
Step 0 : COPY composer.lock /app/user/
 ---> Using cache
Trigger 1, COPY composer.json /app/user/
Step 0 : COPY composer.json /app/user/
 ---> Using cache
Trigger 2, RUN composer install --no-scripts
Step 0 : RUN composer install --no-scripts
 ---> Using cache
Trigger 3, RUN composer show --installed heroku/heroku-buildpack-php || { echo 'Your composer.json must have "heroku/heroku-buildpack-php" as a "require-dev" dependency.'; exit 1; }
Step 0 : RUN composer show --installed heroku/heroku-buildpack-php || { echo 'Your composer.json must have "heroku/heroku-buildpack-php" as a "require-dev" dependency.'; exit 1; }
 ---> Using cache
Trigger 4, ADD . /app/user/
Step 0 : ADD . /app/user/
 ---> Using cache
Trigger 5, RUN cat composer.json | python -c 'import sys,json; sys.exit("post-install-cmd" not in json.load(sys.stdin).get("scripts", {}));' && composer run-script post-install-cmd || true
Step 0 : RUN cat composer.json | python -c 'import sys,json; sys.exit("post-install-cmd" not in json.load(sys.stdin).get("scripts", {}));' && composer run-script post-install-cmd || true
 ---> Using cache
 ---> 427cf28afad4
Successfully built 427cf28afad4
```

Did you `docker pull heroku/php`?

**Comment by triblondon** [comment]
AH! No, I didn't pull `heroku/php`. Sorry. I didn't realise I had to do that, I thought it would check for updates as part of the build.  Works for me now.

**Pull request closed without merging**
